type: seq
required: True
sequence:
  - type: map
    mapping:
      config_type:
        type: text
        required: True
      master_label:
        type: text
        required: True
      help_text:
        type: text
      data_fetch_method:
        type: text
      request_url_template:
        type: text
      request_config:
        type: map
        mapping:
          mode:
            type: text
          callback_parameter_name:
            type: text
      supported_fields:
        type: seq
        sequence:
          - mapping:  
              name:
                type: text
              display_name:
                type: text
              help_text:
                type: text
              input_type:
                type: text
              values:
                type: map
                mapping:
                  value:
                    type: text
                  text:
                    type: text 
