#!/usr/bin/env python
import argparse
from optimizely_dev_tools import help
from optimizely_dev_tools import new
from optimizely_dev_tools import validate

def main():
  parser = argparse.ArgumentParser(description='Optimizely developer tools', prog='opti')
  subparser = parser.add_subparsers()
  
  new_parser = subparser.add_parser('new', description='Create a new Optimizely integration package.')
  new_parser.add_argument('--default_config', action='store_true')
  new_parser.add_argument('-config_type', help='either audience or app', dest='config_type')
  new_parser.add_argument('-package_name', help='name of the package to create', dest='package_name')
  new_parser.set_defaults(func=new.main)

  validate_parser = subparser.add_parser('validate', description='Validate an Optimizely package.')
  validate_parser.add_argument('package_name')
  validate_parser.set_defaults(func=validate.main)

  help_parser = subparser.add_parser('help', description='Open the developer documents related to Optimizely packages in a browser.') 
  help_parser.set_defaults(func=help.main)

  args = parser.parse_args()
  args.func(args)

if __name__ == "__main__":
    main()
